("directories" "symlinks" "ruby" "python" "lisp" "text" "data" "images" "javascript" "html")

(("directories" (:foreground "SteelBlue1") "d.*" 1 nil t nil)
 ("symlinks" (:foreground "LightSkyBlue1") "lrwx" 1 nil t nil)
 ("ruby" (:foreground "indian red") "rb" nil nil nil t)
 ("python" (:foreground "spring green") "py" nil nil nil t)
 ("lisp" (:foreground "chartreuse") "el" nil nil nil t)
 ("text" (:foreground "salmon") "txt text rst markdown" nil nil nil t)
 ("data" (:foreground "gold1") "xml yaml json csv xls" nil nil nil t)
 ("images" (:foreground "slate gray") "jpe?g gif png bmp svg xpm pbm ico xbm ai tiff? " nil nil nil t)
 ("javascript" (:foreground "medium slate blue") "js" nil nil nil t)
 ("html" (:foreground "orange1") "html j2" nil nil nil t))
